workflows:
  update-gitpod-derived-docker-images-using-github-code:
    name: update-gitpod-derived-docker-images-using-github-code
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - docker-hub-credentials
        - github-credentials
    triggering:
      events:
        - push
        - pull_request
        - tag
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      tag_patterns:
        - pattern: '*'
          include: true
    cache:
      cache_paths:
        - $HOME/.pub-cache
    scripts: 
      - name: Install Dart on macOS
        script: |
          brew tap dart-lang/dart
          brew install dart@2.14
          brew link dart@2.14
      - name: update-gitpod-derived-docker-images-using-github-code Sample
        script: |
          dart pub get
          mv .env_sample .env
          export MAXIMUM_DISK_USAGE_PERCENTAGE=60 && dart run update_gitpod_derived_docker_images_using_github_code 'baneeishaque/gitpod-workspace-full-vnc-1366x768-tint2-pcmanfm-zsh-android-studio-gh-chrome'
    publishing:
      email:
        recipients:
          - baneeishaque@gmail.com
          - baneeishaque@hotmail.com
