name: update_gitpod_derived_docker_images_using_github_code
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.11.0-266.0.dev <3.0.0'

dev_dependencies:
  # lints: ^2.0.0
  test: ^1.21.4

dependencies: { docker2: ^2.2.8, http: ^0.13.4, intl: 0.18.1 }
